### PR TITLE
First port of IPublishedContent Properties tested with Alpha 3

### PR DESCRIPTION
**Pull request by Jeavon**

### CODE REVIEW

**Comment by sofietoft** [comment]
Looks great @Jeavon ! Thanks for adding this.

One question: Do we want to continue using `index.md` as the name of the "main" article in a folder? 🤔
I mean, it would make it easier to move stuff over, but since the second file in the folder is using the name of the content in the article as the name of the file as well .. doesn't it make sense that the "index" file follows the same principle?
So, instead of `index.md` it would be `ipublishedcontent.md` instead...
What do you think?

**Comment by bergmania** [comment]
I think `index.md` is a "default" name that is easy to setup, as the one routed to when navigating to the "folder"

**Comment by sofietoft** [comment]
Yeah, that's true @bergmania .
The thing here is, that we're looking into restructuring the docs, to make the structure more flat.
And for this we will actually not be linking to the folders, but to the files instead - in most cases anyways 🤔

**Comment by Jeavon** [comment]
I think that having `index.md` as the starting point for each folder makes it easy to know where to begin when navigating on GitHub. I would stick with it for now, easy to change if we need/want to later

**Comment by sofietoft** [comment]
Ah, yeah. That's a good point.
Forgot about the whole "view docs on Github" there for a second.

Let's merge it in.

**Comment by Jeavon** [comment]
One note for @bergmania was that for a multiple media picker (alias `mediaIds`) it seems there are currently no type converters
e.g. 
Works - `var mediaItems = Model.Value<IEnumerable<IPublishedContent>>("mediaIds");`
Doesn't work - `var mediaIds = Model.Value<IEnumerable<int>>("mediaIds");`

**Comment by bergmania** [comment]
> Works - `var mediaItems = Model.Value<IEnumerable<IPublishedContent>>("mediaIds");`
> Doesn't work - `var mediaIds = Model.Value<IEnumerable<int>>("mediaIds");`

I wouldn't expect any of them to work. What extension method is used?  I would expect you needed to inject `IPublishedValueFallback`

**Comment by Jeavon** [comment]
@bergmania yes, of course, this was the v8 version I was moving over and testing.

In alpha 3 it's like this

`var mediaItems = Model.Value<IEnumerable<IPublishedContent>>(PublishedValueFallback, "mediaIds");`

But 

`var mediaIdsInt = Model.Value<IEnumerable<int>>(PublishedValueFallback, "mediaIds");`

returns null

**Comment by bergmania** [comment]
@Jeavon, there is the `MediaPickerValueConverter` just like in v8? I'm not sure what should be different here. Also v8, will return null for `Model.Value<IEnumerable<int>>(PublishedValueFallback, "mediaIds")` ?

**Comment by Jeavon** [comment]
@bergmania you are right about v8, this took myself and @marcemarc down memory lane, in some versions of v7 it was possible to get a string value `GetPropertyValue<string>("featuredBanner")`  instead of `GetPropertyValue<IPublishedContent>("featuredBanner")` [see here](https://github.com/umbraco/Umbraco-CMS/blob/v7/dev/src/Umbraco.Core/Models/PublishedContent/PublishedContentEnumerable.cs#L36) which returned a csv (e.g. 1231,1212,1221) This was accidentally dropped during the v7 change to store UDIs and no one has ever complained so we will leave it buried in the mists. 
We will also remove this sample from the v8 docs!

**Pull request merged**
