### PR TITLE
Added article for no published content page configuration

### PR DESCRIPTION
**Pull request by AndyButland**
I've put this into a folder `Configuration` under `Articles` - can be re-arranged when there's more articles of course, but it seems like a "Configuration" section will be useful.

### CODE REVIEW

**Comment by bergmania** [comment]
I'm pretty sure the second example in the composer do not work anymore. I'm afraid we don't have an easy way to change the controller currently. I guess you will need to implement remove the `UmbracoRouteValueTransformer` from the container and implement your own.

**Comment by AndyButland** [comment]
OK - don't think this is a critical thing we need to support, rather it was just a nice option at the time.  So I'll remove it from the documentation article.

**Comment by bergmania** [comment]
I agree

**Comment by sofietoft** [comment]
Thanks for moving this one over here 😄 

I agree that putting it in a "Configuration" folder makes sense - at least for now 💪

**Pull request merged**
